l_english:

  civic_machine_experimentor:0 "Radical Experimentors"
  civic_machine_experimentor_effects:0 "Born for science, this machine inteligence will use any means necessary to learn as much as possible."
  civic_machine_experimentor_secondary_species:0 "Test Subjects"